# DEFAULT_OPENAI_MODEL = "openrouter/google/gemini-2.5-flash-lite"
DEFAULT_OPENAI_MODEL = "openrouter/openai/gpt-5-mini"
# DEFAULT_OPENAI_MODEL = "openrouter/openai/gpt-5-nano"
# DEFAULT_OPENAI_MODEL = "openrouter/openai/gpt-4o-mini"

DEFAULT_OPENAI_TIMEOUT = 60.0
DEFAULT_OPENAI_MAX_RETRIES = 10

DEFAULT_DELAY_BETWEEN_SOURCES = 0.5
USE_HARDCODED_SOURCE = False

RATE_LIMIT_MAX_RETRIES = 6
RATE_LIMIT_BASE_DELAY_SECONDS = 5
RATE_LIMIT_JITTER_SECONDS = 3
RATE_LIMIT_REQUESTS_PER_MINUTE = 20
RATE_LIMIT_WINDOW_SECONDS = 60

MCP_DEFAULT_BROWSER = "chromium"
MCP_DEFAULT_HEADLESS = True
MCP_DEFAULT_SSE_TIMEOUT = 50
# MCP_DEFAULT_READY_WAIT_SECONDS = 30
MCP_DEFAULT_TOOL_TIMEOUT_SECONDS = 51
MCP_PLAYWRIGHT_TIMEOUT_SECONDS = 52
MCP_MAX_TURNS = 53

VERBOSE_MCP_LOGGING = False
VERBOSE_AGENT_DECISIONS = False
